### ISSUE TITLE
Storybook Test Failed

### ISSUE THREAD

**Issue by nicosammito** [code0-tech/base-ui#24]
@Taucher2003 as you implemented the testing for storybook I will assign this error to you

![image](https://github.com/code0-tech/base-ui/assets/60352747/e87df582-12aa-439c-ab40-7d1abee61141)

**Comment by Taucher2003** [comment]
This is not a bug. It even says so in the message. It is just that the required browsers are not downloaded yet. You need to run `npx playwright install` and maybe `npx playwright install-deps` (not sure if that is necessary on windows).

After that you should be able to run the tests

**Comment by nicosammito** [comment]
Okay I assumed that they must be installed on the repo scope because on the pipeline they were present. Okay never mind then
